// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.Infrastructure.Data;

#nullable disable

namespace ProjectManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016000143_AddImageProfileToApplicationUser")]
    partial class AddImageProfileToApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ActivityPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<bool?>("AllDay")
                        .HasColumnType("boolean")
                        .HasComment("ทั้งวันหรือไม่");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasComment("ค่าใช้จ่าย");

                    b.Property<string>("CostDetail")
                        .HasColumnType("text")
                        .HasComment("รายละเอียดของค่าใช้จ่าย");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของพนักงาน");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันเวลาที่สิ้นสุด");

                    b.Property<Guid?>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีประเภทกิจกรรม");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HaveCost")
                        .HasColumnType("boolean")
                        .HasComment("มี/ไม่มีค่าใช้จ่าย");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasComment("สถานที่");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasComment("วัตถุประสงค์");

                    b.Property<string>("ObjectiveDetail")
                        .HasColumnType("text")
                        .HasComment("รายละเอียดวัตถุประสงค์");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีหน่วยงาน");

                    b.Property<bool?>("OutSide")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีโปรเจค");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันเวลาที่เริ่มต้น");

                    b.Property<string>("detail")
                        .HasColumnType("text")
                        .HasComment("รายละเอียด");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ActivityPlans");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ActivityPlanAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<Guid>("ActivityPlanId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของการนัดหมาย");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของไฟล์");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityPlanId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("ActivityPlanAttachments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ActivityPlanContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<Guid>("ActivityPlanId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของการนัดหมาย");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationContactId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีหน่วยงาน");

                    b.HasKey("Id");

                    b.HasIndex("ActivityPlanId");

                    b.HasIndex("OrganizationContactId");

                    b.ToTable("ActivityPlanContacts");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageProfile")
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RevokeEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RevokeStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<string>("BucketOriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อที่เก็บไฟล์");

                    b.Property<string>("BucketOriginalPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ที่อยู่ที่เก็บไฟล์");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("นามสกุลไฟล์");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasComment("ขนาดไฟล์");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("NameFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อไฟล์");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ที่อยู่ของไฟล์");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.CheckInCheckOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("เข้างาน");

                    b.Property<int?>("CheckInCheckOutTypes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("ออกงาน");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีพนักงาน");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text")
                        .HasComment("ip เครื่อง");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Lat")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasComment("สถานที่่");

                    b.Property<string>("LocationCheckOut")
                        .HasColumnType("text")
                        .HasComment("สถานที่ออกงาน");

                    b.Property<string>("Long")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีโปรเจค");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีโปรเจค");

                    b.Property<string>("Types")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("CheckInCheckOuts");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.CheckInCheckOutAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของไฟล์");

                    b.Property<Guid>("CheckInCheckOutId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของการนัดหมาย");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CheckInCheckOutId");

                    b.ToTable("CheckInCheckOutAttachments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("การใช้งาน");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อแผนก");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่สร้าง");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้สร้าง");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ลบข้อมูล");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่ปรับปรุง");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ปรับปรุง");

                    b.Property<string>("Massage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefEntityClass")
                        .HasColumnType("text");

                    b.Property<string>("RefEntityId")
                        .HasColumnType("text");

                    b.Property<string>("SendBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("SendStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("SendType")
                        .HasColumnType("text");

                    b.Property<string>("SentTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.EmailMessageSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่สร้าง");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้สร้าง");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ลบข้อมูล");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่ปรับปรุง");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ปรับปรุง");

                    b.Property<string>("MailBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("Sendtime")
                        .HasColumnType("text");

                    b.Property<string>("SettingCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailMessageSettings");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.EmailScheduleSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่สร้าง");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้สร้าง");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ลบข้อมูล");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmailMessageSettingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasComment("สถานะเปิดใช้งาน");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่ปรับปรุง");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ปรับปรุง");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text")
                        .HasComment("ชื่อการกำหนดเวลา");

                    b.Property<DateTime>("SendMailDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("กำหนดวันที่ส่ง");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageSettingId");

                    b.ToTable("EmailScheduleSettings");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของแผนก");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("อีเมล");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasComment("ชื่อ");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("ImageProfile")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasComment("นามสกุล");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasComment("เบอร์โทรศัพท์");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasComment("ตำแหน่ง");

                    b.Property<string>("Roles")
                        .HasColumnType("text");

                    b.Property<bool?>("Subscription")
                        .HasColumnType("boolean");

                    b.Property<string>("TitleName")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้าชื่อ");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสไอดีจากOpenid");

                    b.Property<bool?>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventTypeCode")
                        .HasColumnType("text");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อ");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasComment("ที่อยู่");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text")
                        .HasComment("พิกัด");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Fax")
                        .HasColumnType("text")
                        .HasComment("แฟกซ์");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อหน่วยงาน");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasComment("เบอร์โทร");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasComment("ชื่อย่อหน่วยงาน");

                    b.Property<int?>("TypeOrganization")
                        .HasColumnType("integer")
                        .HasComment("ประเภทหน่วยงาน");

                    b.Property<string>("WebSite")
                        .HasColumnType("text")
                        .HasComment("เว็บไซต์");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.OrganizationContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasComment("อีเมล");

                    b.Property<string>("Fax")
                        .HasColumnType("text")
                        .HasComment("แฟกซ์");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อ");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasComment("นามสกุล");

                    b.Property<string>("LineId")
                        .HasColumnType("text")
                        .HasComment("ไลน์ไอดี");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของหน่วยงาน");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasComment("เบอร์โทร");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasComment("ตำแหน่ง");

                    b.Property<string>("TitleName")
                        .HasColumnType("text")
                        .HasComment("คำนำหน้าชื่อ");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationContacts");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.PlanNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<Guid>("ActivityPlanId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของการนัดหมาย");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("สรุปรายงาน");

                    b.Property<string>("ToDoNext")
                        .HasColumnType("text")
                        .HasComment("สิ่งที่ต้องติดตามต่อ");

                    b.HasKey("Id");

                    b.HasIndex("ActivityPlanId");

                    b.ToTable("PlanNotes");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("text")
                        .HasComment("เลขที่สัญญา");

                    b.Property<DateTime?>("ContractSignedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่ลงนามสัญญา");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่สิ้นสุด");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasComment("หน่วยงาน");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("รหัสโปรเจค");

                    b.Property<decimal?>("ProjectCost")
                        .HasColumnType("numeric")
                        .HasComment("งบประมาณโครงการ");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ชื่อโปรเจค");

                    b.Property<int?>("ProjectType")
                        .HasColumnType("integer")
                        .HasComment("ประเภทโปรเจค");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasComment("ชื่อย่อโปรเจค");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่เริ่มงาน");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่สิ้นสุดรับประกันผลงาน");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ProjectContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationContactId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสไอดีของผู้ติดต่อ");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasComment("รหัสโปรเจค");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationContactId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectContacts");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.SMTPSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("รหัสรายการ");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่สร้าง");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้สร้าง");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ลบข้อมูล");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("วันที่ปรับปรุง");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasComment("ชื่อผู้ปรับปรุง");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int>("SMTPAuthentication")
                        .HasColumnType("integer");

                    b.Property<bool>("SMTPEnableSSL")
                        .HasColumnType("boolean");

                    b.Property<string>("SMTPPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SMTPPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SMTPServer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SMTPUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SMTPSettings");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Reminder")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GCRecord")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ActivityPlan", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Employee", "Employees")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Domain.Entities.EventType", "EventTypes")
                        .WithMany()
                        .HasForeignKey("EventTypeId");

                    b.HasOne("ProjectManagement.Domain.Entities.Organization", "Organizations")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ProjectManagement.Domain.Entities.Project", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Employees");

                    b.Navigation("EventTypes");

                    b.Navigation("Organizations");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ActivityPlanAttachment", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.ActivityPlan", "ActivityPlans")
                        .WithMany("ActivityPlanAttachments")
                        .HasForeignKey("ActivityPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectManagement.Domain.Entities.Attachment", "Attachments")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityPlans");

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ActivityPlanContact", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.ActivityPlan", "ActivityPlan")
                        .WithMany("ActivityPlanContacts")
                        .HasForeignKey("ActivityPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectManagement.Domain.Entities.OrganizationContact", "OrganizationContacts")
                        .WithMany()
                        .HasForeignKey("OrganizationContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityPlan");

                    b.Navigation("OrganizationContacts");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.CheckInCheckOut", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Employee", "Employees")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Domain.Entities.Organization", "Organizations")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ProjectManagement.Domain.Entities.Project", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Employees");

                    b.Navigation("Organizations");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.CheckInCheckOutAttachment", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Attachment", "Attachments")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Domain.Entities.CheckInCheckOut", "CheckInCheckOuts")
                        .WithMany("CheckInCheckOutAttachments")
                        .HasForeignKey("CheckInCheckOutId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Attachments");

                    b.Navigation("CheckInCheckOuts");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.EmailScheduleSetting", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.EmailMessageSetting", "EmailMessageSetting")
                        .WithMany()
                        .HasForeignKey("EmailMessageSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailMessageSetting");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Department", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.OrganizationContact", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Attachment", "Attachments")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("ProjectManagement.Domain.Entities.Organization", "Organizations")
                        .WithMany("OrganizationContacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Attachments");

                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.PlanNote", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.ActivityPlan", "ActivityPlans")
                        .WithMany("PlanNotes")
                        .HasForeignKey("ActivityPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActivityPlans");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Organization", "Organizations")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ProjectContact", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.OrganizationContact", "OrganizationContacts")
                        .WithMany()
                        .HasForeignKey("OrganizationContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Domain.Entities.Project", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationContacts");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.TodoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TodoList", b =>
                {
                    b.OwnsOne("ProjectManagement.Domain.ValueObjects.Colour", "Colour", b1 =>
                        {
                            b1.Property<Guid>("TodoListId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TodoListId");

                            b1.ToTable("TodoLists");

                            b1.WithOwner()
                                .HasForeignKey("TodoListId");
                        });

                    b.Navigation("Colour")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.ActivityPlan", b =>
                {
                    b.Navigation("ActivityPlanAttachments");

                    b.Navigation("ActivityPlanContacts");

                    b.Navigation("PlanNotes");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.CheckInCheckOut", b =>
                {
                    b.Navigation("CheckInCheckOutAttachments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Organization", b =>
                {
                    b.Navigation("OrganizationContacts");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
