/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardAppointmentDetailView: typeof import('./src/components/CardAppointmentDetailView.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CarouselsImage: typeof import('./src/components/CarouselsImage.vue')['default']
    CreateActivityDetail: typeof import('./src/components/CreateActivityDetail.vue')['default']
    CreateActivityPlan: typeof import('./src/components/Activity/CreateActivityPlan.vue')['default']
    CreateOrganization: typeof import('./src/components/OrganizationDialog/CreateOrganization.vue')['default']
    CreateOrganizationContact: typeof import('./src/components/OrganizationDialog/CreateOrganizationContact.vue')['default']
    CRMUltraFeature: typeof import('./src/components/CRMUltraFeature.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GetActivityById: typeof import('./src/components/Activity/GetActivityById.vue')['default']
    ImportFile: typeof import('./src/components/Import/ImportFile.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NationalIdCardReader: typeof import('./src/components/NationalIdCardReader.vue')['default']
    PushNotification: typeof import('./src/components/PushNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextAreaDatepicker: typeof import('./src/components/Datepicker/TextAreaDatepicker.vue')['default']
    TextFieldDatepicker: typeof import('./src/components/Datepicker/TextFieldDatepicker.vue')['default']
    TextFieldTimepicker: typeof import('./src/components/Datepicker/TextFieldTimepicker.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpdateActivityDetail: typeof import('./src/components/Activity/UpdateActivityDetail.vue')['default']
    UpdateAppointmentOutcome: typeof import('./src/components/Activity/UpdateAppointmentOutcome.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
